name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        ports: ['27017:27017']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install backend deps & run tests
        working-directory: backend
        run: |
          npm ci
          npm test

  build-and-push:
    needs: test-backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/minimart-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USER }}/minimart-backend:latest
      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/minimart-frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USER }}/minimart-frontend:latest
